---
# tasks file for cms_config
- name: install cvmfs repo
  apt: deb=https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  tags: ams_config

- name: Install cvmfs packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
       - cvmfs
       - cvmfs-config-default
  tags: ams_config

- name: create/update file /etc/cvmfs/default.local
  blockinfile:
    dest: /etc/cvmfs/default.local
    create: yes
    content: |
      CVMFS_HTTP_PROXY={{ams_config_cvmfs_http_proxy}}
      CVMFS_REPOSITORIES={{ams_config_cvmfs_repositories}}
  tags: ams_config

- name: set AMS_SERVER_URL variable
  lineinfile: dest=/etc/cvmfs/config.d/ams.cern.ch.local create=yes line="CVMFS_SERVER_URL=\"http://cvmfs-stratum-one.cern.ch/opt/@org@\""  
  tags: ams_config

- name: Enable user_allow_other in fuse.conf
  lineinfile: dest=/etc/fuse.conf line="user_allow_other" state=present
  tags: ams_config

- name: Stop autofs
  service: name=autofs state=stopped
  tags: ams_config

- name: Creates CVMFS mountpoint1
  file: path=/cvmfs/ams.cern.ch state=directory owner=cvmfs group=cvmfs recurse=yes
  tags: ams_config

- name: Creates CVMFS mountpoint2
  file: path=/cvmfs/sft.cern.ch state=directory owner=cvmfs group=cvmfs recurse=yes
  tags: ams_config

- name: mount CVMFS1
  command: mount -t cvmfs ams.cern.ch /cvmfs/ams.cern.ch/
  register: result
  until: result | success
  retries: 10
  delay: 10
  tags: ams_config

- name: mount CVMFS2
  command: mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch/
  register: result
  until: result | success
  retries: 10
  delay: 10
  tags: ams_config

###############################
#- name: Set wide-system environment vars
#  blockinfile:
#    dest: /etc/environment
#    create: yes
#    content: |
#      CMS_LOCAL_SITE={{cms_config_cms_local_site}}
#      MYSQUID={{cms_config_mysquid}}
#  tags: cms_config

#- name: Get metricbeat
#  get_url:
#    url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-5.2.2-amd64.deb
#    dest: /tmp/metricbeat.deb
#  tags: metric_install
#
#- name: Install metricbeat
#  command: dpkg -i /tmp/metricbeat.deb
#  tags: metric_install
#
#- name: Get metricbeat config
#  get_url:
#    url: https://gist.githubusercontent.com/dciangot/69b61ff2bb1327b6485af88ac06c71ff/raw/
#    dest: /etc/metricbeat/metricbeat.yml
#    force: yes
#  tags: metric_install
#
#- name: Configure elasticsearch endpoint
#  replace:
#    dest: /etc/metricbeat/metricbeat.yml
#    regexp: '(hosts: )\[\]$'
#    replace: '\1 ["{{monitordb_ip}}"]'
#    backup: yes
#  tags: metric_install
#
#- name: Set metric name
#  replace:
#    dest: /etc/metricbeat/metricbeat.yml
#    regexp: '.*(name:)$'
#    replace: '\1 {{ cms_config_cms_local_site }}'
#    backup: yes
#  tags: metric_install
#
#- name: Set elasticsearch password
#  replace:
#    dest: /etc/metricbeat/metricbeat.yml
#    regexp: '(password:)$'
#    replace: '\1 "{{ cms_config_elastic_secret }}"'
#    backup: yes
#  tags: metric_install
#
#- name: Start metricbeat
#  service:
#    name: metricbeat
#    state: started
#  tags: metric_start

